project_id = "clgztmdjppmbkcfdtxhw"

[functions.edge-assign]
verify_jwt = false

[functions.collect]
verify_jwt = false

[functions.aggregate-events]
verify_jwt = false

[functions.cleanup-data]
verify_jwt = false

[functions.validate-snippet]
verify_jwt = false

[functions.export-archive]
verify_jwt = false
